spring:
  application:
    name: ProductService
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
fakestore:
  api:
    url: https://fakestoreapi:com